[package]
name = "ip-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
nalgebra = "0.33.0"
nalgebra-sparse = "0.10.0"
nalgebra-glm = "0.19.0"
faer = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2.158"
